server:
  port: 1223

spring:
  datasource:
    url: jdbc:mysql://localhost:3308/mybatisdemo
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat


mybatis-plus:
  mapper-locations: com/example/demo/service/persistence/*Mapper.xml
  type-aliases-package: com.example.demo.service.domain
  type-handlers-package: com.example.demo.service.persistence.typehandler


mapper:
  not-empty: false








